[package]
name = "icarus_meta"
version = "0.4.4"
edition = "2024"
rust-version = "1.90"

[dependencies]
lofty = { version = "0.22.4" }
imghdr = { version = "0.7.0" }
infer = { version = "0.19.0" }
rand = { version = "0.9.2" }

[dev-dependencies]
tempfile = { version = "3.23.0" }
